%YAML:1.0

imu0:
  T_i_b:
    - [1.0, 0.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0, 0.0]
    - [0.0, 0.0, 0.0, 1.0]
  # Values from allan plots
  # https://github.com/rpng/ar_table_dataset
  # Inflated values (to account for unmodelled effects)
  #  - white noise multiplied by 5
  #  - bias random walk multiplied by 10
  accelerometer_noise_density: 7.0515172046920914e-04
  accelerometer_random_walk: 7.5070570118600428e-04
  gyroscope_noise_density: 8.6388261041402375e-05
  gyroscope_random_walk: 5.0404868815457580e-05
  model: calibrated
  # rostopic: /imu/data
  # rostopic: /camera/imu
  rostopic_accel: /camera/imu_accel
  rostopic_gyro: /camera/imu_gyro
  time_offset: 0.0
  update_rate: 200


